// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IButton: typeof import('@inkline/inkline')['IButton']
    IHamburgerMenu: typeof import('@inkline/inkline')['IHamburgerMenu']
    ILayout: typeof import('@inkline/inkline')['ILayout']
    ILayoutAside: typeof import('@inkline/inkline')['ILayoutAside']
    ILayoutContent: typeof import('@inkline/inkline')['ILayoutContent']
    ILayoutFooter: typeof import('@inkline/inkline')['ILayoutFooter']
    ILayoutHeader: typeof import('@inkline/inkline')['ILayoutHeader']
    INav: typeof import('@inkline/inkline')['INav']
    INavbar: typeof import('@inkline/inkline')['INavbar']
    INavbarBrand: typeof import('@inkline/inkline')['INavbarBrand']
    INavItem: typeof import('@inkline/inkline')['INavItem']
    ISidebar: typeof import('@inkline/inkline')['ISidebar']
    PhList: typeof import('~icons/ph/list')['default']
    PhListBold: typeof import('~icons/ph/list-bold')['default']
    PhListFill: typeof import('~icons/ph/list-fill')['default']
    PhListThin: typeof import('~icons/ph/list-thin')['default']
    PhRobotThin: typeof import('~icons/ph/robot-thin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
